tests: improve fe_sqr test (issue #1472)
bitcoin-core/secp256k1 pull request #1490
Opened 2024-02-01 01:05 UTC by theStack

As pointed out in issue #1472, currently the `run_sqr` test doesn't do anything with the result of the `fe_sqr` call. Improve that by checking that the equation `(x+y)*(x-y) = x^2 - y^2` holds for some random values y, as suggested by real-or-random in https://github.com/bitcoin-core/secp256k1/issues/1472#issuecomment-1868562354. The existing loop for generating the x values is kept as-is, the sqr call on x is still included in each iteration on the course of calulating the RHS of the equation (`secp256k1_fe_sqr(&rhs, &x);`).

The suggestion says "for random values `y != 0`", but I couldn't see a good reason to exclude zero. Happy to apply s/random_fe_test/random_fe_non_zero_test/ if needed.

2024-02-01 08:48 UTC, real-or-random commented
Nice!

> The suggestion says "for random values `y != 0`", but I couldn't see a good reason to exclude zero. Happy to apply s/random_fe_test/random_fe_non_zero_test/ if needed.

Ah, this is because `fe_mul(_, a, b)` cannot handle the case when `a` is equal to `b`:
https://github.com/bitcoin-core/secp256k1/blob/master/src/field.h#L255-L263

In fact, this is why I suggested the binomial equation. Otherwise, the most natural test would just be  `x*x = x^2`.

I mean, it doesn't matter for truly random `y`, but we should still call `random_fe_non_zero_test` instead. (This reminds me that we could consider biasing the test random function towards zero and other corner cases, but that's a different project...)

2024-02-01 13:05 UTC, real-or-random commented
Oh nevermind, you're right. :D Sorry, this was a brain fart. And indeed, this would be pretty bad.  

Now that you have implemented it, I still think that `(x+y)*(x-y) = x^2 - y^2` is a nice test. It gets us a good test for two sqr operations for the price of 1 mul. ;)

2024-02-01 13:11 UTC, real-or-random approved these changes
utACK b702461a8ddd45c6edcf45627200e52e78985947

2024-02-01 14:00 UTC, real-or-random approved these changes
utACK 7dcb3a8326507c2cd267cda7d333f8e261568f9b

2024-02-27 15:25 UTC, jonasnick approved these changes
ACK 7dcb3a8326507c2cd267cda7d333f8e261568f9b

2024-02-27 15:28 UTC, jonasnick requested changes
Needs rebase (due to `check_fe_equal` not existing anymore in master)

2024-02-27 15:57 UTC, real-or-random approved these changes
utACK 2028069df2e16a05b332ae24c7ae63791f461063

2024-02-27 17:14 UTC, jonasnick approved these changes
ACK 2028069df2e16a05b332ae24c7ae63791f461063

2024-02-27 17:17 UTC, merged