Make autotools check for all the used openssl functions
bitcoin-core/secp256k1 pull request #838
Opened 2020-10-21 11:50 UTC by elichai

I added all the openssl functions that we call in `tests.c` and in `bench_verify.c` to the m4 check, that way if any of them are missing it won't enable openssl.
I also modified it a little to prevent a segmentation fault when running that program (not that it really matters for autotools)

This should fix #836

2020-10-23 16:45 UTC, real-or-random requested changes
`d2i_ECPrivateKey` and `EC_KEY_check_key` (used in `get_openssl_key` in tests.c) are missing.

2020-10-25 11:18 UTC, elichai commented
> `d2i_ECPrivateKey` and `EC_KEY_check_key` (used in `get_openssl_key` in tests.c) are missing.

I have no idea how I missed this, I grepped `ENABLE_OPENSSL_TESTS` multiple times.
Will add now, thanks!

2020-10-25 14:40 UTC, real-or-random approved these changes
ACK e6692778d3f6507eb1325785cdd424073a945ff7 

I've just realized that the summary of build options at the end of configure does not show whether tests are enabled, nor whether OpenSSLs are enabled. If you want, add a commit.

2020-10-27 10:58 UTC, jonasnick commented
> If you want, add a commit.

Do you @elichai ? :) I think that the the author of #836 might have noticed that this was a configure option if it was diplayed in the summary.

2020-10-27 11:11 UTC, elichai commented
Is this what you meant? @real-or-random @jonasnick 

It's also somewhat confusing that everyone calls the library `openssl` but we actually use libcrypto (which is a part of openssl), so the logs say:
```
checking for main in -lcrypto... yes                                                                                  
checking for EC functions in libcrypto... yes                                                                         
```

2020-10-27 13:29 UTC, jonasnick commented on configure.ac
> +    enable_openssl_tests=yes
wrong indentation

2020-10-27 15:42 UTC, real-or-random approved these changes
ACK 3734b68200ee37f5eea80f47d611e9b5a65548fe

2020-10-27 18:10 UTC, sipa commented
ACK 3734b68200ee37f5eea80f47d611e9b5a65548fe

2020-10-27 19:15 UTC, merged